name = "railroad"
description = ""
version = "0.1.0-dev"

authors = ["Gabriel Korzenowski"]
maintainers = ["Gabriel Korzenowski <gabe.korzenowski@gmail.com>"]
licenses = "MIT OR Apache-2.0 WITH LLVM-exception"
website = ""
tags = []

executables = ["railroad"]
